@startuml
'clock clk with period 5
concise "Data" as db
robust "DIO" as dio
robust "Remote\nSample" as st

db is x
st has Vcc,GND
dio has Vcc,GND

scale 200 as 400 pixels

@0
dio is Vcc
st is GND

@+40
dio is GND
st is GND
db is 0
@db
@+0 <-> @+100 : Write "0" Slot
@st
@+0 <-> @+39 : TR
@dio
@+0 <-> @+10 : EN

@+40
st is Vcc
@+1
st is GND
@st
@+1 <-> @+59 : TN

@+5
dio is Vcc

@+59
db is x
dio is {GND,Vcc} #SlateGrey

@enduml