@startuml
'clock clk with period 5
concise "Command" as db

db is x #Slate

scale 30 as 100 pixels

@0

@+10
db is address
@db
@+0 <-> @+40 : 1. Byte

@+40
db is x #Slate
@db
@+0 <-> @+20 : TB

@+20
db is value
@db
@+0 <-> @+40 : 2. Byte

@+40
db is x #Slate
@db
@+0 <-> @+20 : TB

@+20
db is CRC
@db
@+0 <-> @+40 : CRC

@+40
db is x #Slate

@enduml